#!/bin/bash

if [[ $1 == "create" ]]; then
    docker run -itd -v /spare:/spare --name=$2 devbox /bin/bash &>/dev/null && echo "$2 has been successfully created" || echo "$2 could not be created"
elif [[ $1 == "stop" ]]; then
    docker stop $2 &>/dev/null && echo "$2 has been stopped" || echo "$2 could not be stopped"
elif [[ $1 == "start" ]]; then
    docker start $2 &>/dev/null &&  echo "$2 has been started" || echo "$2 could not be started"
elif [[ $1 == "rm" ]]; then
    docker rm -f $2 &>/dev/null && echo "$2 has been removed" || echo "$2 could not be removed"
elif [[ $1 == "attach" ]]; then
    docker exec -it $2 /bin/bash
elif [[ $1 == "list" ]]; then
    check=`docker ps -a`
    echo "${check}" | grep -e 'IMAGE'
    echo "${check}" | grep -e 'devbox'
elif [[ $1 == "ip" ]]; then
    docker inspect $2 | grep "\"IPAddress\"" -m 1 | awk '{print $2}' | cut -d"," -f 1
else
    echo "
devbox [COMMAND] {name}

Manages devboxes on the machine. All system files on devboxes are isolated from each other except /spare.

Following folders are used by each devbox:

/spare/profile: Bash profile that is loaded in the devbox bash
/spare/packages: Common packages can be added here for ease of maintainence
/spare/bin: Manually installed binaries that are present in PATH of all devboxes

COMMANDS:
create: Create a new devbox

start: Start an already existing devbox

stop: Stop a running devbox

rm: Remove a devbox

attach: Attach to the bash of a running devbox instance

list: List all devboxes

ip: Gives the ip address of the devbox
"
fi