#!/bin/bash

if [[ $1 == "create" ]]; then
    XAUTH=$HOME/.Xauthority
    touch $XAUTH
    touch $HOME/.gitconfig
    docker run -itd --network=host --env DISPLAY=$DISPLAY -v /spare:/spare \
    -v $XAUTH:/home/usr/.Xauthority -v $HOME/.gitconfig:/home/usr/.gitconfig \
    -v $HOME/.ssh:/home/usr/.ssh --name=$2 rajatjain1997/devbox /bin/bash \
    &>/dev/null && echo "$2 has been successfully created" || echo "$2 could not be created"
elif [[ $1 == "stop" ]]; then
    docker stop $2 &>/dev/null && echo "$2 has been stopped" || echo "$2 could not be stopped"
elif [[ $1 == "start" ]]; then
    docker start $2 &>/dev/null &&  echo "$2 has been started" || echo "$2 could not be started"
elif [[ $1 == "restart" ]]; then
    docker restart $2 &>/dev/null &&  echo "$2 has been restarted" || echo "$2 could not be restarted"
elif [[ $1 == "rm" ]]; then
    docker rm -f $2 &>/dev/null && echo "$2 has been removed" || echo "$2 could not be removed"
elif [[ $1 == "attach" ]]; then
    docker exec -it $2 /bin/bash
elif [[ $1 == "list" ]]; then
    docker ps --filter ancestor=rajatjain1997/devbox --format "table {{.Names}}\t{{.Status}}\t{{.Size}}" -a
elif [[ $1 == "install" ]]; then
    tag=${2:- "latest"}
    docker pull rajatjain1997/devbox:$tag
elif [[ $1 == "cp" ]]; then
    docker cp $3 $2:$4 
else
    echo "
devbox [COMMAND] {name}

Manages devboxes on the machine. All system files on devboxes are isolated from each other except /spare.

Following folders are used by each devbox:

/spare/.devbox: Bash profile that is loaded in the devbox bash
/spare/packages: Common packages can be added here for ease of maintainence
/spare/bin: Manually installed binaries that are present in PATH of all devboxes

COMMANDS:
install: Install devbox image

create: Create a new devbox

start: Start an already existing devbox

stop: Stop a running devbox

restart: Restart a devbox

rm: Remove a devbox

attach: Attach to the bash of a running devbox instance

list: List all devboxes

cp <devbox name> SRC DEST: Copies files into the devbox from SRC to DEST
"
fi